services:
  postgres:
    image: postgres:18-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql # Persists the data
    ports:
      - "5432:5432"
    networks:
      - my_app_network

  app:
    build: ./backend
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
    networks:
      - my_app_network

  nginx:
    container_name: name
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/frontend
      - ./images:/usr/share/nginx/images

networks:
  my_app_network:
    driver: bridge